### ISSUE TITLE
Contract Pack: SCANSat causes low framerate on Ubuntu

### ISSUE THREAD

**Issue by msholly** [DBT85/CC-CP-SCANSat#5]
I'm running 64 bit Ubuntu with 64 bit KSP. I installed a bunch of mods via CKAN and got a horrible drop in framerate. Maybe 10 FPS when my computer usually runs it at 60. 

I isolated it down to your addin, installing and uninstalling several times to make sure it was the cause. 

Hope this helps, I'd love to run your contracts in my Career game. 

Thanks for your work!

![screenshot from 2015-01-18 21 16 44](https://cloud.githubusercontent.com/assets/3991894/5796178/6633db6c-9f57-11e4-8f7e-38d65be70d8f.png)

**Comment by DBT85** [comment]
Thanks for that @msholly 

That debug looks like its having problems with other parts of Contract Configurator that I'm not using in my pack since it's mentioning the dll which I don't include in the download.

Can I just check that you have the latest version of Contract Configurator, and the dev release (version 9) of SCANSat installed?

I sohuld also check that you are running MY SCANSat pack, and not the one by tattagreis. Mine should appear in GameData/ContractPacks/CC-CP-SCANSat

**Comment by DBT85** [comment]
This has been narrowed down to using the wrong version of the SCANSat mod. Please ensure you are using SCANSAT 9 and above. That is currently the latest DEV build.
